- name: Check if port 9090 is listening prometheus
  wait_for:
    port: 9090
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 9090 to respond"
  register: port_check
  ignore_errors: yes

- name: Check if port 9093 is listening alertmanagers
  wait_for:
    port: 9093
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 9093 to respond"
  register: port_check
  ignore_errors: yes


- name: Check if port 3000 is listening grafana
  wait_for:
    port: 3000
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 3000 to respond"
  register: port_check
  ignore_errors: yes

- name: Check if port 9323 is listening docker_local
  wait_for:
    port: 9323
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 9323 to respond"
  register: port_check
  ignore_errors: yes

- name: Check if port 9100 is listening node
  wait_for:
    port: 9100
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 9100 to respond"
  register: port_check
  ignore_errors: yes

- name: Check if port 8080 is listening cadvisor_local
  wait_for:
    port: 8080
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 8080 to respond"
  register: port_check
  ignore_errors: yes