---
- name: Atualização apt-get repo e cache
  become: true
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Atualização all apt packages
  become: true
  apt: upgrade=dist force_apt_get=yes