global:
  scrape_interval:     10s
  evaluation_interval: 20s
rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'docker_local'
    static_configs:
      - targets: ['localhost:9323']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9100']
  - job_name: 'cadvisor_local'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'alertmanager'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9093']

